
platform:ios,'8.3'
target "YS_iOS_Other" do
pod 'BaiduMapKit','3.0.0'
pod 'Masonry','1.0.1'
pod 'AFNetworking','3.0.0'
pod 'RESideMenu','4.0.7'
pod 'QBImagePickerController','3.4.0'
pod 'UITableView+FDTemplateLayoutCell','1.4'
pod 'CocoaLumberjack','2.3.0'

end

